# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Felix Sperling
tagline:          'Software Engineer. Blogger. Podcaster.'
description:      'Software Engineer. Blogger. Podcaster.'
url:              http://fsperling.github.io
baseurl:          /

author:
  name:           'Felix Sperling'
  url:     

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:   
